### ISSUE TITLE
Make adapter ready for Admin v3

### ISSUE THREAD

**Issue by Apollon77** [angelnu/ioBroker.chromecast#21]
For Admin3 some changes are needed: see http://forum.iobroker.net/viewtopic.php?f=24&t=10268

**Comment by angelnu** [comment]
Version 1.4.0 released wit support for Admin v3.

**Comment by angelnu** [comment]
I need to find out how to update the version with gulp.

**Comment by Apollon77** [comment]
What exactly you mean?
Update Version is 3 things: 
1.) change Version in Package.json
2.) change Version in ip-package.json and add news entry in all languages for the new version
3.) add news info in readme.md

That should it be. Then npm publish

And when  version is proven stable then Update that Version in the repository

**Comment by angelnu** [comment]
I took the gulp file from the admin repo since it was missing before in the template repo. Now that the template is updated I see that they are write different. I will update to the version from the template.

The grunt setup we were using before did more steps to automate the release, including running some checks, updating versions in JavaScript and patching io-package. The gulp setup does a subset of that. On the other hand it seems to patch the news in the readme.

The flow is not so clear on what needs to be done before calling gulp: if I call it before adding the news to io-package then the readme only gets a dummy changelog entry. If I call it after editing the io-package then the coffee to add a news entry would not get used...

**Comment by Apollon77** [comment]
Hm, i Never used the grunt stuff and always did the changes manually. Maybe better to give this feedback in the Forum Thread.

**Comment by angelnu** [comment]
I release version 1.4 with the changes

**Comment by Apollon77** [comment]
Thank you!! Especially that you had some problems as very early adopter :-)
